# Generated by Django 4.2.8 on 2023-12-07 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.CharField(max_length=24, primary_key=True, serialize=False),
                ),
                ("text", models.TextField()),
                ("focos", models.JSONField()),
                ("image", models.URLField(blank=True, null=True)),
                ("video_resolution", models.URLField(blank=True, null=True)),
                ("discipline", models.CharField(max_length=100)),
                ("thematic", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="biology_api_app.question",
                    ),
                ),
            ],
        ),
    ]
